name: 'Sphinx Lint upload'
description: 'Create Annotations from sphinx logs'
author: 'Corentin Jabot'

# Define your inputs here.
inputs:
  path:
    description: 'Path of the sphinx logs'
    required: true
  github-token:
    description: GitHub token for accessing the API
    default: ${{ github.token }}
  name:
    description: 'name of the check'
    default: "Sphinx Lint"

runs:
  using: node16
  main: dist/index.js
